name: Compile PDFs

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Compile
      run: make

    - uses: actions/upload-artifact@v2
      with:
        name: examples
        path: examples/*.pdf
